---
- hosts: tomcatServer
  gather_facts: false
  connection: local
  tasks:
  - name: install the httpd server
    yum: name=httpd state=installed
  - name: server started
    service: name=httpd state=started
    
